export const Users = [
  {
    id: 1,
    profilePicture: "person/1.jpg",
    username: "Ronald Setyadi",
  },
  {
    id: 2,
    profilePicture: "person/2.jpg",
    username: "Fiona",
  },
  {
    id: 3,
    profilePicture: "person/3.jpg",
    username: "Pipin",
  },
  {
    id: 4,
    profilePicture: "person/4.jpg",
    username: "Handy",
  },
  {
    id: 5,
    profilePicture: "person/5.jpg",
    username: "Gina",
  },
  {
    id: 6,
    profilePicture: "person/6.jpg",
    username: "Erick",
  },
  {
    id: 7,
    profilePicture: "person/7.jpg",
    username: "Andi",
  },
  {
    id: 8,
    profilePicture: "person/8.jpg",
    username: "John",
  },
  {
    id: 9,
    profilePicture: "person/9.jpg",
    username: "Boba Fett",
  },
  {
    id: 10,
    profilePicture: "person/10.jpg",
    username: "Jango Fett",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Makan Mandi Tidur",
    photo: "post/1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "post/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Bermain main",
    photo: "post/3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "post/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "post/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "post/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Sedang Liburan",
    photo: "post/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "post/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Berada di Bali",
    photo: "post/9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "post/6.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
